/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * chat-analyzer-api
 * OpenAPI spec version: 2.0.0
 */
export interface AnalysisCreatedResponse {
  analysis_id: string;
  created_at: string;
  status: string;
}

export interface AnalysisListItem {
  analysis_id: string;
  created_at: string;
  phase: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  progress_pct: number;
  status: string;
  updated_at: string;
}

export interface AnalysisListResponse {
  items?: AnalysisListItem[];
}

export type AnalysisStatusResponseErrorCode = string | null;

export type AnalysisStatusResponseErrorMessage = string | null;

export type AnalysisStatusResponseEtaSec = number | null;

export type AnalysisStatusResponsePhase = typeof AnalysisStatusResponsePhase[keyof typeof AnalysisStatusResponsePhase];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisStatusResponsePhase = {
  parsing: 'parsing',
  analyzing: 'analyzing',
  serializing: 'serializing',
  storing: 'storing',
  done: 'done',
  failed: 'failed',
} as const;

export type AnalysisStatusResponseStatus = typeof AnalysisStatusResponseStatus[keyof typeof AnalysisStatusResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisStatusResponseStatus = {
  queued: 'queued',
  running: 'running',
  done: 'done',
  failed: 'failed',
} as const;

export interface AnalysisStatusResponse {
  analysis_id: string;
  error_code?: AnalysisStatusResponseErrorCode;
  error_message?: AnalysisStatusResponseErrorMessage;
  eta_sec?: AnalysisStatusResponseEtaSec;
  phase: AnalysisStatusResponsePhase;
  /**
   * @minimum 0
   * @maximum 100
   */
  progress_pct: number;
  status: AnalysisStatusResponseStatus;
  warnings?: string[];
}

export interface BodyCreateAnalysisApiAnalysesPost {
  file: string;
  timezone?: string;
}

export type ChartConfigAggregation = string | null;

export type ChartConfigFormatters = {[key: string]: string};

export type ChartConfigKind = typeof ChartConfigKind[keyof typeof ChartConfigKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartConfigKind = {
  line: 'line',
  bar: 'bar',
  area: 'area',
  scatter: 'scatter',
  histogram: 'histogram',
} as const;

export type ChartConfigSeries = string | null;

export interface ChartConfig {
  aggregation?: ChartConfigAggregation;
  formatters?: ChartConfigFormatters;
  kind: ChartConfigKind;
  series?: ChartConfigSeries;
  x: string;
  y: string;
}

export type DashboardColumnMetaKind = typeof DashboardColumnMetaKind[keyof typeof DashboardColumnMetaKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardColumnMetaKind = {
  temporal: 'temporal',
  quantitative: 'quantitative',
  ordinal: 'ordinal',
  nominal: 'nominal',
  unknown: 'unknown',
} as const;

export interface DashboardColumnMeta {
  kind: DashboardColumnMetaKind;
  name: string;
}

export type DashboardResponseDatasetMeta = {[key: string]: DatasetMeta};

export type DashboardResponseDatasetsItem = { [key: string]: unknown };

export type DashboardResponseDatasets = {[key: string]: DashboardResponseDatasetsItem[]};

export type DashboardResponseMetadata = { [key: string]: unknown };

export type DashboardResponseSummary = { [key: string]: unknown };

export interface DashboardResponse {
  analysis_id: string;
  dataset_meta?: DashboardResponseDatasetMeta;
  datasets: DashboardResponseDatasets;
  metadata: DashboardResponseMetadata;
  schema_version?: '2.1';
  summary: DashboardResponseSummary;
  tabs: DashboardTab[];
  widgets: DashboardWidget[];
}

export type DashboardTabLayout = typeof DashboardTabLayout[keyof typeof DashboardTabLayout];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardTabLayout = {
  single: 'single',
  'two-column': 'two-column',
  masonry: 'masonry',
} as const;

export interface DashboardTab {
  default_open_sections?: string[];
  id: string;
  layout?: DashboardTabLayout;
  /** @minimum 0 */
  order: number;
  title: string;
}

export type DashboardWidgetChartConfig = ChartConfig | null;

export type DashboardWidgetDataset = string | null;

export type DashboardWidgetEmptyState = string | null;

export type DashboardWidgetFormat = string | null;

export type DashboardWidgetSeverity = 'info' | 'warning' | 'error' | null;

export type DashboardWidgetTableConfig = TableConfig | null;

export type DashboardWidgetText = string | null;

export type DashboardWidgetType = typeof DashboardWidgetType[keyof typeof DashboardWidgetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardWidgetType = {
  chart: 'chart',
  table: 'table',
  kpi: 'kpi',
  text: 'text',
} as const;

export type DashboardWidgetValue = string | number | number | null;

export type DashboardWidgetVegaLiteSpecAnyOf = { [key: string]: unknown };

export type DashboardWidgetVegaLiteSpec = DashboardWidgetVegaLiteSpecAnyOf | null;

export interface DashboardWidget {
  chart_config?: DashboardWidgetChartConfig;
  collapsed_by_default?: boolean;
  dataset?: DashboardWidgetDataset;
  empty_state?: DashboardWidgetEmptyState;
  format?: DashboardWidgetFormat;
  id: string;
  /** @minimum 0 */
  priority?: number;
  section?: string;
  severity?: DashboardWidgetSeverity;
  tab_id: string;
  table_config?: DashboardWidgetTableConfig;
  text?: DashboardWidgetText;
  title: string;
  type: DashboardWidgetType;
  value?: DashboardWidgetValue;
  vega_lite_spec?: DashboardWidgetVegaLiteSpec;
}

export type DatasetMetaRecommendedWidget = typeof DatasetMetaRecommendedWidget[keyof typeof DatasetMetaRecommendedWidget];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatasetMetaRecommendedWidget = {
  chart: 'chart',
  table: 'table',
  both: 'both',
} as const;

export interface DatasetMeta {
  columns?: DashboardColumnMeta[];
  recommended_widget?: DatasetMetaRecommendedWidget;
  /** @minimum 0 */
  row_count: number;
  semantic_kind?: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  sqlite_ok: boolean;
  status: string;
  storage_ok: boolean;
}

export type TableConfigFormat = {[key: string]: string};

export interface TableConfig {
  columns?: string[];
  /**
   * @minimum 1
   * @maximum 500
   */
  default_limit?: number;
  format?: TableConfigFormat;
  sortable?: boolean;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type ListAnalysesApiAnalysesGetParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

/**
 * @summary List Analyses
 */
export type listAnalysesApiAnalysesGetResponse200 = {
  data: AnalysisListResponse
  status: 200
}

export type listAnalysesApiAnalysesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type listAnalysesApiAnalysesGetResponseSuccess = (listAnalysesApiAnalysesGetResponse200) & {
  headers: Headers;
};
export type listAnalysesApiAnalysesGetResponseError = (listAnalysesApiAnalysesGetResponse422) & {
  headers: Headers;
};

export type listAnalysesApiAnalysesGetResponse = (listAnalysesApiAnalysesGetResponseSuccess | listAnalysesApiAnalysesGetResponseError)

export const getListAnalysesApiAnalysesGetUrl = (params?: ListAnalysesApiAnalysesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/analyses?${stringifiedParams}` : `/api/analyses`
}

export const listAnalysesApiAnalysesGet = async (params?: ListAnalysesApiAnalysesGetParams, options?: RequestInit): Promise<listAnalysesApiAnalysesGetResponse> => {
  
  const res = await fetch(getListAnalysesApiAnalysesGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listAnalysesApiAnalysesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAnalysesApiAnalysesGetResponse
}



/**
 * @summary Create Analysis
 */
export type createAnalysisApiAnalysesPostResponse202 = {
  data: AnalysisCreatedResponse
  status: 202
}

export type createAnalysisApiAnalysesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createAnalysisApiAnalysesPostResponseSuccess = (createAnalysisApiAnalysesPostResponse202) & {
  headers: Headers;
};
export type createAnalysisApiAnalysesPostResponseError = (createAnalysisApiAnalysesPostResponse422) & {
  headers: Headers;
};

export type createAnalysisApiAnalysesPostResponse = (createAnalysisApiAnalysesPostResponseSuccess | createAnalysisApiAnalysesPostResponseError)

export const getCreateAnalysisApiAnalysesPostUrl = () => {


  

  return `/api/analyses`
}

export const createAnalysisApiAnalysesPost = async (bodyCreateAnalysisApiAnalysesPost: BodyCreateAnalysisApiAnalysesPost, options?: RequestInit): Promise<createAnalysisApiAnalysesPostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyCreateAnalysisApiAnalysesPost.file)
if(bodyCreateAnalysisApiAnalysesPost.timezone !== undefined) {
 formData.append(`timezone`, bodyCreateAnalysisApiAnalysesPost.timezone)
 }

  const res = await fetch(getCreateAnalysisApiAnalysesPostUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createAnalysisApiAnalysesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createAnalysisApiAnalysesPostResponse
}



/**
 * @summary Delete Analysis
 */
export type deleteAnalysisApiAnalysesAnalysisIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteAnalysisApiAnalysesAnalysisIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteAnalysisApiAnalysesAnalysisIdDeleteResponseSuccess = (deleteAnalysisApiAnalysesAnalysisIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteAnalysisApiAnalysesAnalysisIdDeleteResponseError = (deleteAnalysisApiAnalysesAnalysisIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteAnalysisApiAnalysesAnalysisIdDeleteResponse = (deleteAnalysisApiAnalysesAnalysisIdDeleteResponseSuccess | deleteAnalysisApiAnalysesAnalysisIdDeleteResponseError)

export const getDeleteAnalysisApiAnalysesAnalysisIdDeleteUrl = (analysisId: string,) => {


  

  return `/api/analyses/${analysisId}`
}

export const deleteAnalysisApiAnalysesAnalysisIdDelete = async (analysisId: string, options?: RequestInit): Promise<deleteAnalysisApiAnalysesAnalysisIdDeleteResponse> => {
  
  const res = await fetch(getDeleteAnalysisApiAnalysesAnalysisIdDeleteUrl(analysisId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteAnalysisApiAnalysesAnalysisIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteAnalysisApiAnalysesAnalysisIdDeleteResponse
}



/**
 * @summary Get Analysis Dashboard
 */
export type getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse200 = {
  data: DashboardResponse
  status: 200
}

export type getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponseSuccess = (getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse200) & {
  headers: Headers;
};
export type getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponseError = (getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse422) & {
  headers: Headers;
};

export type getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse = (getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponseSuccess | getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponseError)

export const getGetAnalysisDashboardApiAnalysesAnalysisIdDashboardGetUrl = (analysisId: string,) => {


  

  return `/api/analyses/${analysisId}/dashboard`
}

export const getAnalysisDashboardApiAnalysesAnalysisIdDashboardGet = async (analysisId: string, options?: RequestInit): Promise<getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse> => {
  
  const res = await fetch(getGetAnalysisDashboardApiAnalysesAnalysisIdDashboardGetUrl(analysisId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnalysisDashboardApiAnalysesAnalysisIdDashboardGetResponse
}



/**
 * @summary Get Analysis Status
 */
export type getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse200 = {
  data: AnalysisStatusResponse
  status: 200
}

export type getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponseSuccess = (getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse200) & {
  headers: Headers;
};
export type getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponseError = (getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse422) & {
  headers: Headers;
};

export type getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse = (getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponseSuccess | getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponseError)

export const getGetAnalysisStatusApiAnalysesAnalysisIdStatusGetUrl = (analysisId: string,) => {


  

  return `/api/analyses/${analysisId}/status`
}

export const getAnalysisStatusApiAnalysesAnalysisIdStatusGet = async (analysisId: string, options?: RequestInit): Promise<getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse> => {
  
  const res = await fetch(getGetAnalysisStatusApiAnalysesAnalysisIdStatusGetUrl(analysisId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAnalysisStatusApiAnalysesAnalysisIdStatusGetResponse
}



/**
 * @summary Healthz
 */
export type healthzApiHealthzGetResponse200 = {
  data: HealthResponse
  status: 200
}
    
export type healthzApiHealthzGetResponseSuccess = (healthzApiHealthzGetResponse200) & {
  headers: Headers;
};
;

export type healthzApiHealthzGetResponse = (healthzApiHealthzGetResponseSuccess)

export const getHealthzApiHealthzGetUrl = () => {


  

  return `/api/healthz`
}

export const healthzApiHealthzGet = async ( options?: RequestInit): Promise<healthzApiHealthzGetResponse> => {
  
  const res = await fetch(getHealthzApiHealthzGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthzApiHealthzGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthzApiHealthzGetResponse
}
