/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * chat-analyzer-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../custom-fetch';
export interface AnalysisCreatedResponse {
  analysis_id: string;
  created_at: string;
  status: string;
}

export interface AnalysisListItem {
  analysis_id: string;
  created_at: string;
  phase: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  progress_pct: number;
  status: string;
  updated_at: string;
}

export interface AnalysisListResponse {
  items?: AnalysisListItem[];
}

export type AnalysisStatusResponseErrorCode = string | null;

export type AnalysisStatusResponseErrorMessage = string | null;

export type AnalysisStatusResponseEtaSec = number | null;

export type AnalysisStatusResponsePhase = typeof AnalysisStatusResponsePhase[keyof typeof AnalysisStatusResponsePhase];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisStatusResponsePhase = {
  parsing: 'parsing',
  analyzing: 'analyzing',
  serializing: 'serializing',
  storing: 'storing',
  done: 'done',
  failed: 'failed',
} as const;

export type AnalysisStatusResponseStatus = typeof AnalysisStatusResponseStatus[keyof typeof AnalysisStatusResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisStatusResponseStatus = {
  queued: 'queued',
  running: 'running',
  done: 'done',
  failed: 'failed',
} as const;

export interface AnalysisStatusResponse {
  analysis_id: string;
  error_code?: AnalysisStatusResponseErrorCode;
  error_message?: AnalysisStatusResponseErrorMessage;
  eta_sec?: AnalysisStatusResponseEtaSec;
  phase: AnalysisStatusResponsePhase;
  /**
   * @minimum 0
   * @maximum 100
   */
  progress_pct: number;
  status: AnalysisStatusResponseStatus;
  warnings?: string[];
}

export interface BodyCreateAnalysisApiAnalysesPost {
  file: Blob;
  timezone?: string;
}

export type ChartConfigAggregation = string | null;

export type ChartConfigFormatters = {[key: string]: string};

export type ChartConfigKind = typeof ChartConfigKind[keyof typeof ChartConfigKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartConfigKind = {
  line: 'line',
  bar: 'bar',
  area: 'area',
  scatter: 'scatter',
  histogram: 'histogram',
} as const;

export type ChartConfigSeries = string | null;

export interface ChartConfig {
  aggregation?: ChartConfigAggregation;
  formatters?: ChartConfigFormatters;
  kind: ChartConfigKind;
  series?: ChartConfigSeries;
  x: string;
  y: string;
}

export type DashboardColumnMetaKind = typeof DashboardColumnMetaKind[keyof typeof DashboardColumnMetaKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardColumnMetaKind = {
  temporal: 'temporal',
  quantitative: 'quantitative',
  ordinal: 'ordinal',
  nominal: 'nominal',
  unknown: 'unknown',
} as const;

export interface DashboardColumnMeta {
  kind: DashboardColumnMetaKind;
  name: string;
}

export type DashboardResponseDatasetMeta = {[key: string]: DatasetMeta};

export type DashboardResponseDatasetsItem = { [key: string]: unknown };

export type DashboardResponseDatasets = {[key: string]: DashboardResponseDatasetsItem[]};

export type DashboardResponseMetadata = { [key: string]: unknown };

export type DashboardResponseSummary = { [key: string]: unknown };

export interface DashboardResponse {
  analysis_id: string;
  dataset_meta?: DashboardResponseDatasetMeta;
  datasets: DashboardResponseDatasets;
  metadata: DashboardResponseMetadata;
  schema_version?: '2.1';
  summary: DashboardResponseSummary;
  tabs: DashboardTab[];
  widgets: DashboardWidget[];
}

export type DashboardTabLayout = typeof DashboardTabLayout[keyof typeof DashboardTabLayout];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardTabLayout = {
  single: 'single',
  'two-column': 'two-column',
  masonry: 'masonry',
} as const;

export interface DashboardTab {
  default_open_sections?: string[];
  id: string;
  layout?: DashboardTabLayout;
  /** @minimum 0 */
  order: number;
  title: string;
}

export type DashboardWidgetChartConfig = ChartConfig | null;

export type DashboardWidgetDataset = string | null;

export type DashboardWidgetEmptyState = string | null;

export type DashboardWidgetFormat = string | null;

export type DashboardWidgetSeverity = 'info' | 'warning' | 'error' | null;

export type DashboardWidgetTableConfig = TableConfig | null;

export type DashboardWidgetText = string | null;

export type DashboardWidgetType = typeof DashboardWidgetType[keyof typeof DashboardWidgetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardWidgetType = {
  chart: 'chart',
  table: 'table',
  kpi: 'kpi',
  text: 'text',
} as const;

export type DashboardWidgetValue = string | number | number | null;

export type DashboardWidgetVegaLiteSpecAnyOf = { [key: string]: unknown };

export type DashboardWidgetVegaLiteSpec = DashboardWidgetVegaLiteSpecAnyOf | null;

export interface DashboardWidget {
  chart_config?: DashboardWidgetChartConfig;
  collapsed_by_default?: boolean;
  dataset?: DashboardWidgetDataset;
  empty_state?: DashboardWidgetEmptyState;
  format?: DashboardWidgetFormat;
  id: string;
  /** @minimum 0 */
  priority?: number;
  section?: string;
  severity?: DashboardWidgetSeverity;
  tab_id: string;
  table_config?: DashboardWidgetTableConfig;
  text?: DashboardWidgetText;
  title: string;
  type: DashboardWidgetType;
  value?: DashboardWidgetValue;
  vega_lite_spec?: DashboardWidgetVegaLiteSpec;
}

export type DatasetMetaRecommendedWidget = typeof DatasetMetaRecommendedWidget[keyof typeof DatasetMetaRecommendedWidget];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatasetMetaRecommendedWidget = {
  chart: 'chart',
  table: 'table',
  both: 'both',
} as const;

export interface DatasetMeta {
  columns?: DashboardColumnMeta[];
  recommended_widget?: DatasetMetaRecommendedWidget;
  /** @minimum 0 */
  row_count: number;
  semantic_kind?: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  sqlite_ok: boolean;
  status: string;
  storage_ok: boolean;
}

export type TableConfigFormat = {[key: string]: string};

export interface TableConfig {
  columns?: string[];
  /**
   * @minimum 1
   * @maximum 500
   */
  default_limit?: number;
  format?: TableConfigFormat;
  sortable?: boolean;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type ListAnalysesParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Analyses
 */
export const getListAnalysesUrl = (params?: ListAnalysesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/analyses?${stringifiedParams}` : `/api/analyses`
}

export const list_analyses = async (params?: ListAnalysesParams, options?: RequestInit): Promise<AnalysisListResponse> => {
  
  return customFetch<AnalysisListResponse>(getListAnalysesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListAnalysesQueryKey = (params?: ListAnalysesParams,) => {
    return [
    `/api/analyses`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAnalysesQueryOptions = <TData = Awaited<ReturnType<typeof list_analyses>>, TError = HTTPValidationError>(params?: ListAnalysesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list_analyses>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAnalysesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof list_analyses>>> = ({ signal }) => list_analyses(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof list_analyses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAnalysesQueryResult = NonNullable<Awaited<ReturnType<typeof list_analyses>>>
export type ListAnalysesQueryError = HTTPValidationError


export function useListAnalyses<TData = Awaited<ReturnType<typeof list_analyses>>, TError = HTTPValidationError>(
 params: undefined |  ListAnalysesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof list_analyses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list_analyses>>,
          TError,
          Awaited<ReturnType<typeof list_analyses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAnalyses<TData = Awaited<ReturnType<typeof list_analyses>>, TError = HTTPValidationError>(
 params?: ListAnalysesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list_analyses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list_analyses>>,
          TError,
          Awaited<ReturnType<typeof list_analyses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAnalyses<TData = Awaited<ReturnType<typeof list_analyses>>, TError = HTTPValidationError>(
 params?: ListAnalysesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list_analyses>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Analyses
 */

export function useListAnalyses<TData = Awaited<ReturnType<typeof list_analyses>>, TError = HTTPValidationError>(
 params?: ListAnalysesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list_analyses>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAnalysesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create Analysis
 */
export const getCreateAnalysisUrl = () => {


  

  return `/api/analyses`
}

export const create_analysis = async (bodyCreateAnalysisApiAnalysesPost: BodyCreateAnalysisApiAnalysesPost, options?: RequestInit): Promise<AnalysisCreatedResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyCreateAnalysisApiAnalysesPost.file)
if(bodyCreateAnalysisApiAnalysesPost.timezone !== undefined) {
 formData.append(`timezone`, bodyCreateAnalysisApiAnalysesPost.timezone)
 }

  return customFetch<AnalysisCreatedResponse>(getCreateAnalysisUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getCreateAnalysisMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create_analysis>>, TError,{data: BodyCreateAnalysisApiAnalysesPost}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof create_analysis>>, TError,{data: BodyCreateAnalysisApiAnalysesPost}, TContext> => {

const mutationKey = ['createAnalysis'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create_analysis>>, {data: BodyCreateAnalysisApiAnalysesPost}> = (props) => {
          const {data} = props ?? {};

          return  create_analysis(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAnalysisMutationResult = NonNullable<Awaited<ReturnType<typeof create_analysis>>>
    export type CreateAnalysisMutationBody = BodyCreateAnalysisApiAnalysesPost
    export type CreateAnalysisMutationError = HTTPValidationError

    /**
 * @summary Create Analysis
 */
export const useCreateAnalysis = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create_analysis>>, TError,{data: BodyCreateAnalysisApiAnalysesPost}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create_analysis>>,
        TError,
        {data: BodyCreateAnalysisApiAnalysesPost},
        TContext
      > => {

      const mutationOptions = getCreateAnalysisMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete Analysis
 */
export const getDeleteAnalysisUrl = (analysisId: string,) => {


  

  return `/api/analyses/${analysisId}`
}

export const delete_analysis = async (analysisId: string, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getDeleteAnalysisUrl(analysisId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteAnalysisMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete_analysis>>, TError,{analysisId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof delete_analysis>>, TError,{analysisId: string}, TContext> => {

const mutationKey = ['deleteAnalysis'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof delete_analysis>>, {analysisId: string}> = (props) => {
          const {analysisId} = props ?? {};

          return  delete_analysis(analysisId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAnalysisMutationResult = NonNullable<Awaited<ReturnType<typeof delete_analysis>>>
    
    export type DeleteAnalysisMutationError = HTTPValidationError

    /**
 * @summary Delete Analysis
 */
export const useDeleteAnalysis = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete_analysis>>, TError,{analysisId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof delete_analysis>>,
        TError,
        {analysisId: string},
        TContext
      > => {

      const mutationOptions = getDeleteAnalysisMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get Analysis Dashboard
 */
export const getGetAnalysisDashboardUrl = (analysisId: string,) => {


  

  return `/api/analyses/${analysisId}/dashboard`
}

export const get_analysis_dashboard = async (analysisId: string, options?: RequestInit): Promise<DashboardResponse> => {
  
  return customFetch<DashboardResponse>(getGetAnalysisDashboardUrl(analysisId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAnalysisDashboardQueryKey = (analysisId?: string,) => {
    return [
    `/api/analyses/${analysisId}/dashboard`
    ] as const;
    }

    
export const getGetAnalysisDashboardQueryOptions = <TData = Awaited<ReturnType<typeof get_analysis_dashboard>>, TError = HTTPValidationError>(analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_dashboard>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalysisDashboardQueryKey(analysisId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof get_analysis_dashboard>>> = ({ signal }) => get_analysis_dashboard(analysisId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(analysisId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof get_analysis_dashboard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalysisDashboardQueryResult = NonNullable<Awaited<ReturnType<typeof get_analysis_dashboard>>>
export type GetAnalysisDashboardQueryError = HTTPValidationError


export function useGetAnalysisDashboard<TData = Awaited<ReturnType<typeof get_analysis_dashboard>>, TError = HTTPValidationError>(
 analysisId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_dashboard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof get_analysis_dashboard>>,
          TError,
          Awaited<ReturnType<typeof get_analysis_dashboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalysisDashboard<TData = Awaited<ReturnType<typeof get_analysis_dashboard>>, TError = HTTPValidationError>(
 analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_dashboard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof get_analysis_dashboard>>,
          TError,
          Awaited<ReturnType<typeof get_analysis_dashboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalysisDashboard<TData = Awaited<ReturnType<typeof get_analysis_dashboard>>, TError = HTTPValidationError>(
 analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_dashboard>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Analysis Dashboard
 */

export function useGetAnalysisDashboard<TData = Awaited<ReturnType<typeof get_analysis_dashboard>>, TError = HTTPValidationError>(
 analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_dashboard>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalysisDashboardQueryOptions(analysisId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get Analysis Status
 */
export const getGetAnalysisStatusUrl = (analysisId: string,) => {


  

  return `/api/analyses/${analysisId}/status`
}

export const get_analysis_status = async (analysisId: string, options?: RequestInit): Promise<AnalysisStatusResponse> => {
  
  return customFetch<AnalysisStatusResponse>(getGetAnalysisStatusUrl(analysisId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAnalysisStatusQueryKey = (analysisId?: string,) => {
    return [
    `/api/analyses/${analysisId}/status`
    ] as const;
    }

    
export const getGetAnalysisStatusQueryOptions = <TData = Awaited<ReturnType<typeof get_analysis_status>>, TError = HTTPValidationError>(analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_status>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalysisStatusQueryKey(analysisId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof get_analysis_status>>> = ({ signal }) => get_analysis_status(analysisId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(analysisId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof get_analysis_status>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalysisStatusQueryResult = NonNullable<Awaited<ReturnType<typeof get_analysis_status>>>
export type GetAnalysisStatusQueryError = HTTPValidationError


export function useGetAnalysisStatus<TData = Awaited<ReturnType<typeof get_analysis_status>>, TError = HTTPValidationError>(
 analysisId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_status>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof get_analysis_status>>,
          TError,
          Awaited<ReturnType<typeof get_analysis_status>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalysisStatus<TData = Awaited<ReturnType<typeof get_analysis_status>>, TError = HTTPValidationError>(
 analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_status>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof get_analysis_status>>,
          TError,
          Awaited<ReturnType<typeof get_analysis_status>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalysisStatus<TData = Awaited<ReturnType<typeof get_analysis_status>>, TError = HTTPValidationError>(
 analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_status>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Analysis Status
 */

export function useGetAnalysisStatus<TData = Awaited<ReturnType<typeof get_analysis_status>>, TError = HTTPValidationError>(
 analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof get_analysis_status>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalysisStatusQueryOptions(analysisId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Healthz
 */
export const getHealthzUrl = () => {


  

  return `/api/healthz`
}

export const healthz = async ( options?: RequestInit): Promise<HealthResponse> => {
  
  return customFetch<HealthResponse>(getHealthzUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getHealthzQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }

    
export const getHealthzQueryOptions = <TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthzQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthz>>> = ({ signal }) => healthz({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthzQueryResult = NonNullable<Awaited<ReturnType<typeof healthz>>>
export type HealthzQueryError = unknown


export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Healthz
 */

export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthzQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
